export enum BookCopyStatus {
  AVAILABLE = 'AVAILABLE',
  RESERVED = 'RESERVED',
  READY_FOR_COLLECTION = 'READY_FOR_COLLECTION',
  BORROWED = 'BORROWED',
  OVERDUE = 'OVERDUE',
  LOST = 'LOST',
  DAMAGED = 'DAMAGED',
}
